print("Name",":Shaan Jose")
print("University",  ":Bath Spa")
name=input("Enter Name:")
print(name)
age=input("Enter Age:")
print (age)
University=input("Enter University:")
print(University)
sex=input("Enter Sex:")
print(sex)
print((2*3/8+(23+5)))